steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/chip-multi', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/chip-multi']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'chip-multi', '--image', 'gcr.io/$PROJECT_ID/chip-multi', '--region', 'us-east1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/chip-multi

